window:
  width: 1750
  height: 900
  background: 0, 0, 0
  main_font:
    name: freesansbold.ttf
    color: 0, 255, 64
    size: 32
  secondary_font:
    name: freesansbold.ttf
    color: 0, 255, 64
    size: 20

paddings:
  left: 400
  right: 30
  bottom: 80
  top: 80
  inner: 10

figure:
  border_width: 2
  chart_color: 255, 255, 255
  border_color: 0, 255, 64

data:
  count: 50

main_loop:
  fps: 30
